<a href="https://colab.research.google.com/github/Jhow3D/Python---M-dulo-3---An-lise-dedados-/blob/main/Aula_1_Python_M%C3%B3dulo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np 

In [34]:
minhaLista = [0,1,2,3,4,5,6,8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 8]

In [35]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 8])

In [36]:
print(meuArray)

[0 1 2 3 4 5 6 8]


In [37]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [38]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
array3 = np.arange(0,10,0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [41]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [42]:
array3 = np.arange(0,10,0.5,dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
array4 = np.arange(12)

In [44]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [45]:
type(array4)

numpy.ndarray

In [46]:
array4.dtype

dtype('float64')

In [47]:
vetor1 = np.array([0,1,2,3,4])
print(vetor1)

[0 1 2 3 4]


In [48]:
vetor1[3]

3

In [49]:
vetor1[0:2]

array([0, 1])

In [50]:
print(vetor1[0:2])

[0 1]


In [51]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [52]:
vetor1[0] = 45.0
vetor1

array([45,  1, 10,  3,  4])

In [53]:
minhaMatriz = np.array([[1,2,3], [4,5,6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
minhaLista = [[13,81,22],[0,34,59],[21,48,94]]
minhaLista

[[13, 81, 22], [0, 34, 59], [21, 48, 94]]

In [55]:
minhaMatriz = np.matrix(minhaLista)
minhaMatriz


matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [56]:
x = np.zeros(3)
x

array([0., 0., 0.])

In [57]:
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [58]:
print(np.zeros(3))

[0. 0. 0.]


In [59]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [60]:
x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [62]:
y = np.array([[8,8,8,8],[8,8,8,8],[8,8,8,8],[8,8,8,8]])
y

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [63]:
y = np.ones((4,4))*8
y

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [65]:
z = np.diag(np.array([1,2,3,4,5,6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [66]:
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
y = np.eye(5, dtype=int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [68]:
np.shape(minhaMatriz)

(3, 3)

In [69]:
type(minhaMatriz)

numpy.matrix

In [70]:
minhaMatriz.dtype

dtype('int64')

In [71]:
minhaMatriz[2,1]

48

In [72]:
print(minhaMatriz[0,:])

[[13 81 22]]


In [73]:
print(minhaMatriz[:,2])

[[22]
 [59]
 [94]]


In [74]:
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [75]:
np. sum(meuArray)

29

In [76]:
np.prod(meuArray)

0

In [77]:
np.cumsum(meuArray)

array([ 0,  1,  3,  6, 10, 15, 21, 29])

In [79]:
array1.min()

0

In [80]:
array1.max()

8

In [81]:
np.mean(meuArray)

3.625

In [82]:
np.median(meuArray)

3.5

In [83]:
np.var(meuArray)

6.234375

In [84]:
np.std(meuArray)

2.496873044429772